/*** SOME MORE WORTH LOOKING AT 
 
- FIND & FINDC
- IFC & IFN
- STRIP
- COALESCE & COALESEC
- FILENAME fileref CLIPBOARD ;
- PROC PROTO & PROC FCMP
- PROC SYLK
- PROC EXPORT SHEET=
- %SYMEXIST
- LIBNAME libref META
- _NEW_
- OPTION MPRINTNEST

***/